version: "3"
services:
  backend:
    image: junmop950/total-hub-site:backend-latest
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVE_PROFILE: ${SPRING_ACTIVE_PROFILE}
      SPRING_DATABASE_USERNAME: ${SPRING_DATABASE_USERNAME}
      SPRING_DATABASE_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      JWT_SECRET_KEY1: ${JWT_SECRET_KEY1}
      JWT_SECRET_KEY2: ${JWT_SECRET_KEY2}
      JWT_SECRET_KEY3: ${JWT_SECRET_KEY3}
  frontend:
    image: junmop950/total-hub-site:frontend-latest
    ports:
      - "80:80"
  rabbitmq:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
