version: "3"
services:
  application:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:backend-latest
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVE_PROFILE: ${SPRING_ACTIVE_PROFILE}
      SPRING_DATABASE_USERNAME: ${SPRING_DATABASE_USERNAME}
      SPRING_DATABASE_PASSWORD: ${SPRING_DATABASE_PASSWORD}
